[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.2.0"

[[constraint]]
  name = "github.com/franela/goblin"
  version = "0.0.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"
